export type TypeScale =
    | "Display-large"
    | "Display-medium"
    | "Display-small"
    | "Headline-large"
    | "Headline-medium"
    | "Headline-small"
    | "Title-large"
    | "Title-medium"
    | "Title-small"
    | "Label-large"
    | "Label-medium"
    | "Label-small"
    | "Body-large"
    | "Body-medium"
    | "Body-small";
